CREATE TABLE t_board 
(
  board_idx NUMBER PRIMARY KEY,
  title VARCHAR2(300) NOT NULL,
  contents_dtl CLOB NOT NULL,
  hit_cnt NUMBER DEFAULT 0 NOT NULL,
  created_dt DATE NOT NULL,
  creator_id VARCHAR2(50) NOT NULL,
  updated_dt DATE DEFAULT NULL,
  updater_id VARCHAR2(50) DEFAULT NULL,
  deleted_yn CHAR(1) DEFAULT 'N' NOT NULL
);

COMMENT ON COLUMN SPRINGTEST.t_board.board_idx IS '글 번호';
COMMENT ON COLUMN SPRINGTEST.t_board.title IS '제목';
COMMENT ON COLUMN SPRINGTEST.t_board.contents_dtl IS '내용';
COMMENT ON COLUMN SPRINGTEST.t_board.hit_cnt IS '조회수';
COMMENT ON COLUMN SPRINGTEST.t_board.created_dt IS '작성시간';
COMMENT ON COLUMN SPRINGTEST.t_board.creator_id IS '작성자';
COMMENT ON COLUMN SPRINGTEST.t_board.updated_dt IS '수정시간';
COMMENT ON COLUMN SPRINGTEST.t_board.updater_id IS '수정자';
COMMENT ON COLUMN SPRINGTEST.t_board.deleted_yn IS '삭제 여부';


CREATE SEQUENCE BOARD_IDX_SEQ INCREMENT BY 1 START WITH 1;


CREATE OR REPLACE TRIGGER T_BOARD_TRIG
BEFORE INSERT
ON T_BOARD
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
SELECT BOARD_IDX_SEQ.nextval INTO :NEW.BOARD_IDX FROM dual;
END;

CREATE TABLE T_FILE
(
	IDX NUMBER PRIMARY KEY,
	BOARD_IDX NUMBER NOT NULL,
	ORIGINAL_FILE_NAME VARCHAR2(255) NOT NULL,
	STORED_FILE_PATH VARCHAR2(500) NOT NULL,
	FILE_SIZE NUMBER NOT NULL,
	CREATOR_ID VARCHAR2(50) NOT NULL,
	CREATED_DT DATE NOT NULL,
	UPDATER_ID VARCHAR2(50) DEFAULT NULL,
	UPDATED_DT DATE DEFAULT NULL,
	DELETED_YN CHAR(1) DEFAULT 'N' NOT NULL
	);

COMMENT ON COLUMN T_FILE.IDX IS '일련번호';
COMMENT ON COLUMN T_FILE.BOARD_IDX IS '게시글 번호';
COMMENT ON COLUMN T_FILE.ORIGINAL_FILE_NAME IS '원본 파일 이름';
COMMENT ON COLUMN T_FILE.STORED_FILE_PATH IS '파일 저장 경로';
COMMENT ON COLUMN T_FILE.FILE_SIZE IS '파일 크기';
COMMENT ON COLUMN T_FILE.CREATOR_ID IS '작성자 아이디';
COMMENT ON COLUMN T_FILE.CREATED_DT IS '작성시간';
COMMENT ON COLUMN T_FILE.UPDATER_ID IS '수정자 아이디';
COMMENT ON COLUMN T_FILE.UPDATED_DT IS '수정시간';
COMMENT ON COLUMN T_FILE.deleted_yn IS '삭제 여부';	



CREATE SEQUENCE T_FILE_IDX_SEQ INCREMENT BY 1 START WITH 1;

CREATE OR REPLACE TRIGGER T_FILE_TRIG
BEFORE INSERT
ON T_FILE
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
SELECT T_FILE_IDX_SEQ.nextval INTO :NEW.IDX FROM dual;
END;

CREATE TABLE ROLE(
	ROLE_ID NUMBER PRIMARY KEY,
	ROLE VARCHAR2(255) DEFAULT NULL,
);

CREATE SEQUENCE SEQ_ROLE INCREMENT BY 1 START WITH 1;

CREATE TABLE USER(
	USER_ID NUMBER PRIMARY KEY,
	ACTIVE NUMBER DEFAULT 0,
	LOGIN_ID VARCHAR2(255) NOT NULL,
	USER_NAME VARCHAR2(255) NOT NULL,
	PASSWORD VARCHAR2(255) NOT NULL,
);

CREATE SEQUENCE SEQ_USER INCREMENT BY 1 START WITH 1; 

CREATE TABLE USER_ROLE(
	USER_ID NUMBER NOT NULL,
	ROLE_ID NUMBER NOT NULL,
	CONSTRAINT PK_USER_ROLE PRIMARY KEY (USER_ID, ROLE_ID) USING INDEX
);
